apps:
    maya:
        addon_types:
            modules:
            -   path: '{project_branch_path}/addons/maya/modules/psyhive'
                restrictions:
                    version:
                    -   2018*