"""Constants for qt tools."""

from psyhive.qt.wrapper import QtGui

COLS = [
    "AliceBlue",
    "AntiqueWhite",
    "Aqua",
    "Aquamarine",
    "Azure",
    "Beige",
    "Bisque",
    "Black",
    "BlanchedAlmond",
    "Blue",
    "BlueViolet",
    "Brown",
    "BurlyWood",
    "CadetBlue",
    "Chartreuse",
    "Chocolate",
    "Coral",
    "CornflowerBlue",
    "Cornsilk",
    "Crimson",
    "Cyan",
    "DarkBlue",
    "DarkCyan",
    "DarkGoldenrod",
    "DarkGray",
    "DarkGreen",
    "DarkGrey",
    "DarkKhaki",
    "DarkMagenta",
    "DarkOliveGreen",
    "DarkOrange",
    "DarkOrchid",
    "DarkRed",
    "DarkSalmon",
    "DarkSeaGreen",
    "DarkSlateBlue",
    "DarkSlateGray",
    "DarkSlateGrey",
    "DarkTurquoise",
    "DarkViolet",
    "DeepPink",
    "DeepSkyBlue",
    "DimGray",
    "DimGrey",
    "DodgerBlue",
    "FireBrick",
    "FloralWhite",
    "ForestGreen",
    "Fuchsia",
    "Gainsboro",
    "GhostWhite",
    "Gold",
    "Goldenrod",
    "Gray",
    "Green",
    "GreenYellow",
    "Grey",
    "Honeydew",
    "HotPink",
    "IndianRed",
    "Indigo",
    "Ivory",
    "Khaki",
    "Lavender",
    "LavenderBlush",
    "LawnGreen",
    "LemonChiffon",
    "LightBlue",
    "LightCoral",
    "LightCyan",
    "LightGoldenrodYellow",
    "LightGray",
    "LightGreen",
    "LightGrey",
    "LightPink",
    "LightSalmon",
    "LightSeaGreen",
    "LightSkyBlue",
    "LightSlateGray",
    "LightSlateGrey",
    "LightSteelBlue",
    "LightYellow",
    "Lime",
    "LimeGreen",
    "Linen",
    "Magenta",
    "Maroon",
    "MediumAquamarine",
    "MediumBlue",
    "MediumOrchid",
    "MediumPurple",
    "MediumSeaGreen",
    "MediumSlateBlue",
    "MediumSpringGreen",
    "MediumTurquoise",
    "MediumVioletRed",
    "MidnightBlue",
    "MintCream",
    "MistyRose",
    "Moccasin",
    "NavajoWhite",
    "Navy",
    "OldLace",
    "Olive",
    "OliveDrab",
    "Orange",
    "OrangeRed",
    "Orchid",
    "PaleGoldenrod",
    "PaleGreen",
    "PaleTurquoise",
    "PaleVioletRed",
    "PapayaWhip",
    "PeachPuff",
    "Peru",
    "Pink",
    "Plum",
    "PowderBlue",
    "Purple",
    "Red",
    "RosyBrown",
    "RoyalBlue",
    "SaddleBrown",
    "Salmon",
    "SandyBrown",
    "SeaGreen",
    "Seashell",
    "Sienna",
    "Silver",
    "SkyBlue",
    "SlateBlue",
    "SlateGray",
    "SlateGrey",
    "Snow",
    "SpringGreen",
    "SteelBlue",
    "Tan",
    "Teal",
    "Thistle",
    "Tomato",
    "Turquoise",
    "Violet",
    "Wheat",
    "White",
    "WhiteSmoke",
    "Yellow",
    "YellowGreen",
]

NICE_COLS = [
    'salmon', 'tomato', 'darksalmon', 'coral', 'orangered', 'lightsalmon',
    'sandybrown', 'darkorange', 'orange', 'goldenrod', 'gold', 'yellow',
    'olivedrab', 'yellowgreen', 'darkolivegreen', 'greenyellow', 'chartreuse',
    'lawngreen', 'darkgreen', 'forestgreen', 'green', 'lightgreen', 'lime',
    'limegreen', 'palegreen', 'mediumseagreen', 'seagreen', 'springgreen',
    'mediumspringgreen', 'aquamarine', 'mediumaquamarine', 'turquoise',
    'lightseagreen', 'mediumturquoise', 'cyan', 'darkcyan', 'darkslategrey',
    'darkturquoise', 'teal', 'cadetblue', 'powderblue', 'lightblue',
    'deepskyblue', 'lightskyblue', 'steelblue', 'dodgerblue',
    'lightslategrey', 'slategray', 'slategrey', 'lightsteelblue',
    'cornflowerblue', 'royalblue', 'blue', 'darkblue', 'mediumblue',
    'midnightblue', 'navy', 'darkslateblue', 'mediumslateblue', 'slateblue',
    'mediumpurple', 'blueviolet', 'indigo', 'darkorchid', 'darkviolet',
    'mediumorchid', 'darkmagenta', 'magenta', 'plum', 'purple', 'thistle',
    'violet', 'orchid', 'mediumvioletred', 'deeppink', 'hotpink',
    'palevioletred', 'crimson', 'pink', 'lightpink']

BLANK = QtGui.QColor(0, 0, 0, 0)
